[docs]

title = "ReVanced Releases API"
description = """
This website provides a JSON API for ReVanced Releases 🚀

Changelogs are not included but can be found on the [ReVanced Repositories](https://github.com/revanced/).

The team also have a [Discord Server](https://revanced.app/discord) if you need help.

## API Endpoints

* [tools](/tools) - Returns the latest version of all ReVanced tools and Vanced MicroG
* [patches](/patches) - Returns the latest version of all ReVanced patches
* [contributors](/contributors) - Returns contributors for all ReVanced projects

## Additional Information

* Rate Limiting - 15 requests per minute
* Cache - 5 minutes

## Important Notes

1. Although we will try to avoid breaking changes, we can't guarantee that it won't happen.
2. Okay, the api is now cached and rate limited (per endpoint). But please don't abuse it, we don't want to have to block you.
3. Make sure to implement a cache system on your end to avoid unnecessary requests.

Godspeed 💀

"""
version = "0.2 alpha"

[license]

name = "AGPL-3.0"
url = "https://www.gnu.org/licenses/agpl-3.0.en.html"

[uvicorn]

host = "0.0.0.0"
port = 8000

[slowapi]

limit = "15/minute"

[cache]
expire = 60
database = 0

[internal-cache]
expire = 300
database = 1

[app]

repositories = ["TeamVanced/VancedMicroG", "revanced/revanced-cli", "revanced/revanced-patches", "revanced/revanced-integrations", "revanced/revanced-manager", "revanced/revanced-patcher"]