[docs]
title = "ReVanced Releases API"
description = """
## The official JSON API for ReVanced Releases 🚀

### Links

- [Changelogs](https://github.com/revanced/)
- [Official links to ReVanced](https://revanced.app)

### Important Information

* Rate Limiting - 60 requests per minute
* Cache - 5 minutes
* Token duration - 1 year

### Additional Notes

1. Breaking changes are to be expected
2. Client side caching is advised to avoid unnecessary requests
3. Abuse of the API will result in IP blocks

"""
version = "1.2.0"

[license]
name = "AGPL-3.0"
url = "https://www.gnu.org/licenses/agpl-3.0.en.html"

[logging]
level = "INFO"
json_logs = false

[cache]
expire = 300
database = 0

[slowapi]
limit = "60/minute"
database = 1

[clients]
database = 2

[tokens]
database = 3

[announcements]
database = 4

[mirrors]
database = 5

[auth]
access_token_expires = false

[app]
repositories = ["revanced/revanced-patcher", "revanced/revanced-patches", "revanced/revanced-integrations", "revanced/revanced-manager", "revanced/revanced-cli", "revanced/revanced-website", "revanced/revanced-releases-api"]

[socials]
website = "https://revanced.app"
github = "https://github.com/revanced"
twitter = "https://twitter.com/revancedapp"
discord = "https://revanced.app/discord"
reddit = "https://www.reddit.com/r/revancedapp"
telegram = "https://t.me/app_revanced"
youtube = "https://www.youtube.com/@ReVanced"
