[docs]

title = "ReVanced Releases API"
description = """
This website provides a JSON API for ReVanced Releases 🚀

Changelogs are not included but can be found on the [ReVanced Repositories](https://github.com/revanced/).

The team also have a [Discord Server](https://revanced.app/discord) if you need help.

## Important Information

* Rate Limiting - 60 requests per minute
* Cache - 5 minutes

## Additional Notes

1. Although we will try to avoid breaking changes, we can't guarantee that it won't happen.
2. Okay, the api is now cached and rate limited (per endpoint). But please don't abuse it, we don't want to have to block you.
3. Make sure to implement a cache system on your end to avoid unnecessary requests.

Godspeed 💀

"""
version = "0.5.2 beta"

[license]

name = "AGPL-3.0"
url = "https://www.gnu.org/licenses/agpl-3.0.en.html"

[uvicorn]

host = "0.0.0.0"
port = 8000

[slowapi]

limit = "60/minute"

[logging]

level = "INFO"
json_logs = false

[cache]
expire = 120
database = 0

[internal-cache]
expire = 300
database = 1

[clients]
database = 2

[tokens]
database = 3

[announcements]
database = 4

[app]

repositories = ["TeamVanced/VancedMicroG", "revanced/revanced-cli", "revanced/revanced-patcher", "revanced/revanced-patches", "revanced/revanced-integrations", "revanced/revanced-manager"]

