---
version: "3.8"

volumes:
  redis-data:
    driver: local

services:
  redis:
    container_name: revanced-releases-api-redis
    image: redis:latest
    volumes:
      - redis-data:/data
    networks:
      - infra
    restart: always
  revanced-releases-api:
    container_name: revanced-releases-api
    image: alexandreteles/revanced-releases-api:latest
    environment:
      - GITHUB_TOKEN=YOUR_GITHUB_TOKEN
      - REDIS_URL=revanced-releases-api-redis
      - REDIS_PORT=6379
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000
      - UVICORN_LOG_LEVEL=debug
      - SENTRY_DSN=YOUR_SENTRY_DSN
    ports:
      - 127.0.0.1:7934:8000
    networks:
      - infra
    restart: unless-stopped

networks:
   infra:
     external: true